openapi: 3.0.0
info:
  version: '1'
  title: HowtolistAttributes
  description: "Manifest to retrieve attributes needed to make requests to HowToList.
    HowToList manifest - https://github.com/rollun-lc/openapi-manifests/blob/master/shipping_methods__v1.yml"
servers:
  - url: http://catalog/openapi/HowtolistAttributes/v1
tags:
  - name: Attributes
    description: "Tag for endpoints related to attributes"
paths:
  /attributes:
    get:
      tags:
        - Attributes
      summary: "Retrieve attributes by csn and supplier"
      description: "Retrieve by csn and supplier attributes needed to make requests to HTL"
      parameters:
        - name: supplier
          in: query
          required: true
          description: "Name of supplier in which we should lookup requested csn"
          schema:
            type: string
            enum:
              - "Autodist"
              - "PartsUnlimited"
              - "RockyMountain"
              - "Turn14"
              - "Wps"
        - name: csn
          in: query
          required: true
          schema:
            type: string
          example: "AWA3775C"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HtlAttributesResponse"
        "500":
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        messages:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - INVALID_RESPONSE
          description: >
            UNDEFINED - Any undefined message type
            INVALID_RESPONSE - A message generated by the client stating that the response could not be decoded
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResponse:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      type: object
      properties:
        data:
          type: object
    HtlAttributesResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
      properties:
        data:
          $ref: '#/components/schemas/HtlAttributes'

    HtlAttributes:
      type: object
      properties:
        weight:
          type: number
          example: 1.0
        width:
          type: number
          example: 2.0
        length:
          type: number
          example: 3.5
        height:
          type: number
          example: 4.0
        isDangerous:
          description: 'Whether the package contains hazardous materials. It is necessary to determine the possibility of sending by air.'
          type: boolean
          example: false
          nullable: true
        isTire:
          description: 'Flag affects the validator'
          type: boolean
          example: false
          nullable: true
        # RM
        rmCategory:
          description: 'Category for RM, affects the price'
          type: string
          example: 'Filters'
          nullable: true
        rmIsKit:
          description: 'IsKit for RM, affects the price'
          type: boolean
          example: false
          nullable: true
        rmFee:
          description: 'A fee of RM, affects the price'
          type: number
          example: 10.2
          nullable: true
        rmIsOversize:
          description: 'Flag IsOversize for RM, affects the price'
          type: string
          enum:
            - Y
            - N
          example: Y
          nullable: true
        # AU
        auIsFirstClass:
          description: 'If possible, then send a parcel First Class'
          type: string
          enum:
            - Y
            - N
          example: Y
          nullable: true
        auFlatRateGroup:
          description: 'Flag affects the price'
          type: string
          example: ATV25
          nullable: true
        auLargePackageSurcharge:
          description: 'Flag affects the price'
          type: number
          example: 10.2
          nullable: true
        # PU
        puCommodityCode:
          description: 'Commodity Code for PU affects the price'
          type: string
          nullable: true
          example: '0319'
        # WPS
        wpsCategory:
          description: 'Wps Category. Tubes, Tires, Wheels'
          type: string
          nullable: true
          example: 'Tubes'
        wpsDropShipFee:
          description: 'Shipping Price. Enum - FR, 18, 12, 35..'
          type: string
          nullable: true
          example: '9.75'

