openapi: 3.0.0
info:
  version: "1"
  title: "ProductSetup"
  description: Openapi to add product to catalog, create rid for it, create mappings between rid and csn, etc.
servers:
  - url: http://catalog/openapi/ProductSetup/v1
tags:
  - name: CreateRid
paths:
  "/rid":
    put:
      tags:
        - CreateRid
      summary: "Create rid for product and add this product to catalog"
      description: "1. Create rid by supplier name and csn (ignores existing rid), 
        2. then add mappings for every existing csn to created rid (ignores existing mappings), 
        3. then send product to suppliers main caches for every existing csn"
      parameters:
        - name: supplierName
          in: query
          required: true
          description: "Name of supplier that will be used to create rid for product"
          example: "Autodist"
          schema:
            type: string
            enum:
              - Autodist
              - Keystone
              - PartsUnlimited
              - RockyMountain
              - RollunOffice
              - Turn14
              - Wps
        - name: csn
          in: query
          required: true
          description: "Id of product in provided supplier that will be used to create rid"
          example: "909022"
          schema:
            type: string
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RidCreationResponse"
        "500":
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        messages:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - INVALID_RESPONSE
          description: >
            UNDEFINED - Any undefined message type
            INVALID_RESPONSE - A message generated by the client stating that the response could not be decoded
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResponse:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      type: object
      properties:
        data:
          type: object
    RidCreationResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
      properties:
        data:
          type: object
          allOf:
            - $ref: '#/components/schemas/RidCreationInfo'

    ## Resource object
    RidCreationInfo:
      type: object
      required:
        - rid
        - processedMappings
        - csnsSentToCache
      properties:
        ridStatus:
          type: object
          nullable: false
          allOf:
            - $ref: '#/components/schemas/RidStatus'
        processedMappings:
          type: array
          nullable: false
          items:
            $ref: '#/components/schemas/RidToCsnMapping'
        csnsSentToCache:
          type: array
          nullable: false
          items:
            $ref: '#/components/schemas/SupplierCsn'

    RidToCsnMapping:
      type: object
      required:
        - rid
        - supplierName
        - csn
        - status
      properties:
        rid:
          type: string
          nullable: false
          example: "6R4BK"
        supplierName:
          type: string
          nullable: false
          example: "Autodist"
          enum:
            - Autodist
            - Keystone
            - PartsUnlimited
            - RockyMountain
            - RollunOffice
            - Turn14
            - Wps
        csn:
          type: string
          nullable: false
          example: "909022"
        status:
          type: string
          nullable: false
          example: "created"
          enum:
            - existed
            - created
            - problem

    SupplierCsn:
      type: object
      required:
        - supplierName
        - csn
      properties:
        supplierName:
          type: string
          nullable: false
          example: "Autodist"
          enum:
            - Autodist
            - Keystone
            - PartsUnlimited
            - RockyMountain
            - RollunOffice
            - Turn14
            - Wps
        csn:
          type: string
          nullable: false
          example: "909022"

    RidStatus:
      type: object
      required:
        - rid
        - status
      properties:
        rid:
          type: string
          nullable: false
          example: "6R4BK"
        status:
          type: string
          nullable: false
          example: "created"
          enum:
            - existed
            - created
