openapi: 3.0.0
info:
  version: "1"
  title: "ProductInfoBySuppliers"
  description: Openapi to retrieve product info by supplier from catalog
servers:
  - url: http://catalog/openapi/ProductInfoBySuppliers/v1
tags:
  - name: SupplierPrice
paths:
  "/product/prices":
    get:
      tags:
        - SupplierPrice
      summary: "Get product prices by brand and mpn for every supplier"
      parameters:
        - name: brand
          in: query
          required: true
          description: '' #todo
          example: "WSM"
          schema:
            type: string
        - name: mpn
          in: query
          required: true
          description: '' #todo
          example: "002-048-01"
          schema:
            type: string
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SupplierProductPricesResponse"
        "500":
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        messages:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - INVALID_RESPONSE
          description: >
            UNDEFINED - Any undefined message type
            INVALID_RESPONSE - A message generated by the client stating that the response could not be decoded
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResponse:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      type: object
      properties:
        data:
          type: object
    SupplierProductPricesResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/SupplierProductPrices'

    ## Resource object
    SupplierProductPrices:
      type: object
      required:
        - supplierName
        - csn
      properties:
        supplierName:
          type: string
          nullable: false
        csn:
          type: string
          nullable: false
        rid:
          type: string
          nullable: true
        dealerPrice:
          type: number
          nullable: true
        totalQty:
          type: integer
          nullable: true
        shippingOptions:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/ShippingOption'

    ShippingOption:
      type: object
      properties:
        deliverySender:
          type: string
          example: "wps_ds"
        shippingMethodId:
          type: string
          example: "PU-PickUp-Usps-PM-FR-BgBox"
        shippingMethodName:
          type: string
          example: "Priority Mail Large Flat Rate Board Game Box"
        cost:
          type: number
          example: 5.84
          nullable: true
        trackNumberDate:
          type: string
          example: "2020-01-30T09:00:00Z"
        shippingArriveDate:
          type: string
          nullable: true
          example: "2020-02-03T09:00:00Z"
        shippingSendDate:
          type: string
          example: "2020-02-03T09:00:00Z"
        carrier:
          type: string
          enum:
            - Usps
            - Fedex
            - Ups
          example: Fedex
          nullable: true