openapi: 3.0.0
info:
  version: "1"
  title: "ProductAspects"
  description: Get chosen product aspects by rid
servers:
  - url: http://catalog/openapi/ProductAspects/v1
  - url: http://service-catalog.loc/openapi/ProductAspects/v1
tags:
  - name: Aspects

paths:
  "/aspects/getByRids":
    post:
      tags:
        - Aspects
      summary: "Get chosen product aspects by rid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AspectsRequest'
      parameters:
        - name: recalculate
          in: query
          required: false
          description: "Attention: currently not implemented.
              If true - value will be recalculated from scratch, bypassing cache"
          schema:
            type: boolean
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AspectsResponse"
        "500":
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        messages:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - INVALID_RESPONSE
            - NO_STRATEGY
            - MISSING_DATA
          description: >
            UNDEFINED - Any undefined message type
            INVALID_RESPONSE - A message generated by the client stating that the response could not be decoded
            NO_STRATEGY - There is no strategy to compute requested value
            MISSING_DATA - Some crucial data is missing to generate valid response
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResponse:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      type: object
      properties:
        data:
          type: object
    AspectsResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
      properties:
        data:
          type: array
          nullable: false
          items:
            allOf:
              - $ref: '#/components/schemas/Aspects'

    AspectsRequest:
      type: object
      required:
        - rids
      properties:
        rids:
          type: array
          nullable: false
          items:
            type: string
          example: ["12IUP","RC18A"]
        aspects:
          type: array
          nullable: true
          items:
            type: string
            # todo enum

    ## Resource object
    Aspects:
      type: object
      required:
        - rid
      properties:
        rid:
          type: string
          nullable: false
          example: "RC18A"
        brand:
          type: string
          nullable: true
          example: "PIRELLI"
        mpn:
          type: string
          nullable: true
          example: "3659100"
        aspectRatio:
          type: string
          nullable: true
          example: "100"
        sectionWidth:
          type: string
          nullable: true
          example: "80"
        wheelDiameter:
          type: string
          nullable: true
          example: "12"
        loadIndex:
          type: string
          nullable: true
          example: "50"
        speedIndex:
          type: string
          nullable: true
          example: "M"
