openapi: 3.0.0
info:
  version: "1"
  title: "SuppliersWarehouses"
  description: Suppliers warehouses
servers:
  - url: http://suppliers/openapi/Suppliers/v1
tags:
  - name: Warehouse
paths:
  "/warehousesWithDistance":
    get:
      tags:
        - Warehouse
      summary: "Get list of orders"
      description: "Get list of orders"
      parameters:
        - in: query
          name: "zipTo"
          description: "Client zip5 code. The distance will be calculated between this zip code and the warehouse"
          required: true
          schema:
            type: string
            example: "44216"
      responses:
        "200":
          description: "Success"
          content:
            aplication/json:
              schema:
                $ref: "#/components/schemas/WarehouseWithDistanceListResult"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResult"
        '500':
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
components:
  schemas:
    ErrorResult:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - info
            - warning
            - error
        type:
          type: string
          enum:
            - UNDEFINED
            - LOGGER_MESSAGE
          description: >
            UNDEFINED - Any undefined message type
            LOGGER_MESSAGE - Same as undefined 
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResult:
      allOf:
        - $ref: '#/components/schemas/ErrorResult'
      type: object
      properties:
        data:
          type: object

    ## Order results
    WarehouseWithDistanceListResult:
      allOf:
        - $ref: '#/components/schemas/SuccessResult'
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/WarehouseWithDistance'

    ## Resources
    WarehouseWithDistance:
      allOf:
        - $ref: '#/components/schemas/Warehouse'
      type: object
      properties:
        distance:
          type: number
          description: Distance in meters from the warehouse, to the specified zip code.
          example: 1170191.06598
        zipTo:
          type: string
          description: zip5 code
          example: "44216"
        sortedPosition:
          type: integer
          description: The position of this warehouse in a list sorted by handling_time and distance. The lower the number, the more priority the warehouse.
          example: 0
    
    Warehouse:
      type: object
      properties:
        id:
          type: string
          description: Unique identificator. In format "suplierAbbreviation_warehouseName"
          example: "PU_NC"
        supplierName:
          type: string
          description: Name of supplier (same as id from https://rollun.net/suppliers)
          example: PartsUnlimited
        warehouseName:
          type: string
          description: Warehouse name
          example: NC
        zip:
          type: string
          description: zip5 code
          example: "28731"
        handling_time:
          type: string
          description: Warehouse orders processing speed. Alphabetically (A is the best, Z is the worst)
          example: A